#!groovy

@Library("workflowlibs@1.13.0") _

pipeline {

    agent none

    options {
        ansiColor('xterm')
        buildDiscarder(logRotator(
            // number of builds to keep
            numToKeepStr:         env.BRANCH_NAME ==~ /master/ ? '10' :
                                  env.BRANCH_NAME ==~ /PR-.*|feature\/.*|fix\/.*/ ? '3' : '1',
        ))
        disableResume()
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }

    stages {
        stage('Checkout Global Library') {
            steps {
                script{
                    globalBootstrap {
                        libraryName   = "cellsworkflowlibs"
                        libraryBranch = "2.1.5-cs.7"

                        entrypointParams = [
                            type              : "cellsComponent",
                            logLevel          : "ERROR",
                            lint              : true,
                            abortOnLintFailure: true,
                            sonarQube         : true,
                            test              : true,
                            cellsConfig: [
                                storeLogs: true
                            ],
                            extended          : [
                                integrationPattern : [
                                    master: "^(feature|fix)/.+",
                                ],
                                upgradeVersion  : true
                            ],
                            samuelExtra: [
                                owners: ["d.rodriguez.guillen@bbva.com", "eneas.gallego.contractor@bbva.com", "adrianojose.martin.contractor@bbva.com"],
                                applyGroups: "glomo-component-base",
                                projectJira: "GLOMOGL,GLOMOAR,GLOMOMX,GLOMOPE,GLOMOUY",
                                projectSamuel: "glomo"
                            ],
                            deployConfig: [
                                deployArtifactory: true,
                                artifactoryConfig: [
                                    deployConfig: [branchRegEx: ["master"], repository: "gl-glomo-bower", adminCredentialId: "bot-glomo-artifactory", userCredentialId: "glomo-artifactory" ]
                                ]
                            ],
                            samuelAnalysis: true,
                            sonarConfig: [ qualityProfile: 'cells.app', qualityGate: 'glomo.app', waitForQualityGate: true ],
                            updateConfig       : [
                                updateFiles: true,
                                jenkinsConfig: [
                                    jobUpdate: "job/CLIENT_SOLUTIONS/job/RETAIL_CUSTOMERS/job/GloMo/job/BBVA_RETAIL_GLOMO_AUTOMATIZATIONS/job/UTILS/job/UPDATE_JENKINSFILE",
                                    endPoint: "https://globaldevtools.bbva.com/piaas-gl-apps-cells"
                                ]
                            ]
                        ]
                    }
                }
            }
        }
    }
}